more init script refactoring

diff --git a/board/common/overlay/etc/init.d/functions b/board/common/overlay/etc/init.d/functions
--- a/board/common/overlay/etc/init.d/functions
+++ b/board/common/overlay/etc/init.d/functions
@@ -1,3 +1,14 @@
 #!/bin/bash
 
+msg_begin() {
+    echo -n "$1: "
+}
+
+msg_done() {
+    test -n "$1" && echo $1 || echo "done"
+}
+
+msg_fail() {
+    test -n "$1" && echo $1 || echo "failed"
+}
 
