.gitlab-ci.yml: use "extends" keyword
Replace all YAML anchors with the new "extends" keyword because it is
more readable and more flexible (it works across configuration files
combined with the new "include" keyword).

Readability is more meaningful in .gitlab-ci.yml.in.
In the part of .gitlab-ci.yml that is auto-generated by 'make
.gitlab-ci.yml' keep the keyword in the same line of the job name.
So instead of this:
 zynqmp_zcu106_defconfig:
     extends: .defconfig
 tests.boot.test_atf.TestATFAllwinner:
     extends: .runtime_test
Use this:
 zynqmp_zcu106_defconfig: { extends: .defconfig }
 tests.boot.test_atf.TestATFAllwinner: { extends: .runtime_test }
Do this to to keep .gitlab-ci.yml easier to be post-processed by a
script.

Signed-off-by: Ricardo Martincoski <ricardo.martincoski@gmail.com>
Cc: Arnout Vandecappelle <arnout@mind.be>
Cc: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>

diff --git a/.gitlab-ci.yml.in b/.gitlab-ci.yml.in
--- a/.gitlab-ci.yml.in
+++ b/.gitlab-ci.yml.in
@@ -6,16 +6,17 @@
 
 image: buildroot/base:20180318.1724
 
-.defconfig_script: &defconfig_script
-    - echo 'Configure Buildroot'
-    - make ${CI_JOB_NAME}
-    - echo 'Build buildroot'
-    - |
-        make > >(tee build.log |grep '>>>') 2>&1 || {
-            echo 'Failed build last output'
-            tail -200 build.log
-            exit 1
-        }
+.defconfig_script:
+    script:
+        - echo 'Configure Buildroot'
+        - make ${CI_JOB_NAME}
+        - echo 'Build buildroot'
+        - |
+            make > >(tee build.log |grep '>>>') 2>&1 || {
+                echo 'Failed build last output'
+                tail -200 build.log
+                exit 1
+            }
 
 check-gitlab-ci.yml:
     script:
@@ -45,14 +46,14 @@ check-package:
     script:
         - make check-package
 
-.defconfig: &defconfig
+.defconfig:
+    extends: .defconfig_script
     # Running the defconfigs for every push is too much, so limit to
     # explicit triggers through the API.
     only:
         - triggers
         - tags
         - /-defconfigs$/
-    script: *defconfig_script
     artifacts:
         when: always
         expire_in: 2 weeks
@@ -64,7 +65,7 @@ check-package:
             - output/build/packages-file-list.txt
             - output/build/*/.config
 
-.runtime_test: &runtime_test
+.runtime_test:
     # Running the runtime tests for every push is too much, so limit to
     # explicit triggers through the API.
     only:
