skalibs: bump version to 2.5.1.1
Signed-off-by: Eric Le Bihan <eric.le.bihan.dev@free.fr>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>

diff --git a/package/skalibs/0002-No-runtime-tests-for-type-sizes.patch b/package/skalibs/0002-No-runtime-tests-for-type-sizes.patch
--- a/package/skalibs/0002-No-runtime-tests-for-type-sizes.patch
+++ b/package/skalibs/0002-No-runtime-tests-for-type-sizes.patch
@@ -1,6 +1,6 @@
-From d868600a3f437750bc44a783d677a25a48100096 Mon Sep 17 00:00:00 2001
-From: Eric Le Bihan <eric.le.bihan.dev@free.fr>
-Date: Sun, 4 Dec 2016 19:11:25 +0100
+From 2596155d76e4f2a3eab45ef7d095ade996b8b2a5 Mon Sep 17 00:00:00 2001
+From: "Van Bemten, Lionel (Nokia - BE/Antwerp)" <lionel.van_bemten@nokia.com>
+Date: Thu, 18 May 2017 19:38:46 +0200
 Subject: [PATCH] No runtime tests for type sizes
 
 Replace build and execution of runtime test programs for determining
@@ -8,47 +8,101 @@ some type sizes of the target with compile time test programs.
 
 This improves support for cross-compilation.
 
+Signed-off-by: "Van Bemten, Lionel (Nokia - BE/Antwerp)" <lionel.van_bemten@nokia.com>
 Signed-off-by: Eric Le Bihan <eric.le.bihan.dev@free.fr>
 ---
- configure | 24 +++++++++++++++++++++---
- 1 file changed, 21 insertions(+), 3 deletions(-)
+ configure | 74 ++++++++++++++++++++++++++++++++++++++++++++++++++-------------
+ 1 file changed, 59 insertions(+), 15 deletions(-)
 
 diff --git a/configure b/configure
-index 4da9c5e..b5926ca 100755
+index 5fffc34..115fea3 100755
 --- a/configure
 +++ b/configure
-@@ -157,10 +157,28 @@ choose () {
+@@ -154,25 +154,69 @@ choose () {
+   fi
+ }
  
- trytypesize () {
-   echo "Checking size of $3..."
--  $CC_AUTO $CPPFLAGS_AUTO $CFLAGS_AUTO $LDFLAGS_AUTO -o trysizeof$1 src/sysdeps/trysizeof$1.c
--  type_size=$(./trysizeof$1) || fail "$0: unable to determine size of $3"
++findtypesize () {
++  typ=$1
++  abbr=$2
 +  r=false
 +  type_size=0
 +  while true; do
-+    cat<<EOF>trysizeof$1.c
++    cat>trysizeof${abbr}.c<<EOF
 +#include <sys/types.h>
 +
 +int main(void)
 +{
-+  static int v = 1 / !!((sizeof($3) == $type_size));
++  static int v = 1 / !!((sizeof($typ) == $type_size));
 +  return 0;
 +}
 +EOF
-+    if $CC_AUTO $CPPFLAGS_AUTO $CFLAGS_AUTO $LDFLAGS_AUTO -o trysizeof$1 trysizeof$1.c 2>/dev/null; then
++    if $CC_AUTO $CPPFLAGS_AUTO $CFLAGS_AUTO $LDFLAGS_AUTO -o trysizeof${abbr} trysizeof${abbr}.c 2>/dev/null; then
 +        r=true
 +        break
 +    fi
 +    type_size=$(expr $type_size + 1)
 +    test $type_size -le 16 || break
 +  done
-+  test $r = true || fail "$0: unable to determine size of $3"
-   type_bits=$(expr 8 \* $type_size)
--  rm -f trysizeof$1
-+  rm -f trysizeof$1 trysizeof$1.c
-   echo "sizeof$1: $type_size" >> $sysdeps/sysdeps
-   echo "#define ${package_macro_name}_SIZEOF$2 $type_size" >> $sysdeps/sysdeps.h
-   echo "#define ${package_macro_name}_$2_BITS $type_bits" >> $sysdeps/sysdeps.h
++  rm -f trysizeof${abbr} trysizeof${abbr}.c
++  test $r = true || fail "$0: unable to determine size of $typ"
++  caps=$(echo "sizeof${abbr}" | tr a-z A-Z)
++  echo "#define ${package_macro_name}_${caps} $type_size" >> $sysdeps/sysdeps.h
++  echo "sizeof${abbr}: $type_size" >> $sysdeps/sysdeps
++}
++
++findtypesign () {
++  typ=$1
++  abbr=$2
++  caps=$(echo "signed${abbr}" | tr a-z A-Z)
++  cat>trysignof${abbr}.c<<EOF
++#include <sys/types.h>
++
++int main(void)
++{
++  static int v = 1 / !!(((($typ) -1) < 0));
++  return 0;
++}
++EOF
++  if $CC_AUTO $CPPFLAGS_AUTO $CFLAGS_AUTO $LDFLAGS_AUTO -o trysignof${abbr} trysignof${abbr}.c 2>/dev/null; then
++    echo "#define ${package_macro_name}_HASSIGNED${caps}" >> $sysdeps/sysdeps.h
++    echo "#undef ${package_macro_name}_HASUNSIGNED${caps}" >> $sysdeps/sysdeps.h
++    echo "signed${abbr}: yes" >> $sysdeps/sysdeps
++  else
++    echo "#undef ${package_macro_name}_HASSIGNED${caps}" >> $sysdeps/sysdeps.h
++    echo "#define ${package_macro_name}_HASUNSIGNED${caps}" >> $sysdeps/sysdeps.h
++    echo "signed${abbr}: no" >> $sysdeps/sysdeps
++  fi
++  rm -f trysignof${abbr} trysignof${abbr}.c
++}
++
+ trytypes () {
+   echo "Checking size and signedness of standard types..."
+-  $CC_AUTO $CPPFLAGS_AUTO $CFLAGS_AUTO $LDFLAGS_AUTO -o output-types src/sysdeps/output-types.c
+-  ./output-types >> $sysdeps/sysdeps
+-  ./output-types | grep -F sizeof | while read key value ; do
+-    caps=$(echo $key | sed s/:\$// | tr a-z A-Z)
+-    echo "#define ${package_macro_name}_${caps} $value" >> $sysdeps/sysdeps.h
++  for t in "unsigned short" "unsigned int" "unsigned long"; do
++    findtypesize "$t" "${t/nsigned /}"
+   done
+-  ./output-types | grep -F signed | while read key value ; do
+-    caps=$(echo $key | sed s/:\$// | tr a-z A-Z)
+-    if test $value = yes ; then
+-      echo "#define ${package_macro_name}_HASSIGNED${caps}"
+-      echo "#undef ${package_macro_name}_HASUNSIGNED${caps}"
+-    else
+-      echo "#undef ${package_macro_name}_HASSIGNED${caps}"
+-      echo "#define ${package_macro_name}_HASUNSIGNED${caps}"
+-    fi >> $sysdeps/sysdeps.h
++  for t in size uid gid pid time dev ino; do
++    findtypesize "${t}_t" "$t"
++    findtypesign "${t}_t" "$t"
+   done
+-  rm -f output-types
+   echo "  ... done"
+ }
+ 
 -- 
-2.5.5
+2.9.3
 
