olsr: bump to version 0.6.8
Also:

* Add hash file
* Rename patch to new naming convention
* Revamp/cleanup initscript
* Install sample config to the correct location

Signed-off-by: Gustavo Zacarias <gustavo@zacarias.com.ar>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>

diff --git a/package/olsr/S50olsr b/package/olsr/S50olsr
--- a/package/olsr/S50olsr
+++ b/package/olsr/S50olsr
@@ -1,21 +1,23 @@
 #!/bin/sh
-#
-# Starts OLSRD daemon
-#
 
 case "$1" in
   start)
-  	echo "Starting OLSRd daemon: "
-	/usr/sbin/olsrd -d 0
-	;;
+    echo -n "Starting oslrd daemon: "
+    start-stop-daemon -S -q -x /usr/sbin/olsrd -- -d 0 -pidfile /run/olsrd.pid
+    [ $? = 0 ] && echo "OK" || echo "FAIL"
+    ;;
   stop)
-  	echo "Stopping OLSRd daemon: "
-	killall olsrd
-	;;
+    echo -n "Stopping olsrd daemon: "
+    start-stop-daemon -K -q -p /run/olsrd.pid
+    [ $? = 0 ] && echo "OK" || echo "FAIL"
+    ;;
+  restart)
+    $0 stop
+    $0 start
+    ;;
   *)
-	echo "Usage: $0 {start|stop}"
-	exit 1
+    echo "Usage: $0 {start|stop|restart}"
+    exit 1
 esac
 
 exit $?
-
