inadyn: bump to version 1.99.11
Update initscript for the /usr/sbin -> /usr/bin change which is the
default installation directory now that it's using autotools infra.
Also add hash file.
Make the initscript use tabs instead of spaces.
Make the config file installation conditional.
Now with optional gnutls support for HTTPS.

Signed-off-by: Gustavo Zacarias <gustavo@zacarias.com.ar>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>

diff --git a/package/inadyn/S70inadyn b/package/inadyn/S70inadyn
--- a/package/inadyn/S70inadyn
+++ b/package/inadyn/S70inadyn
@@ -13,23 +13,24 @@ VR_INADYN=/var/run/inadyn
 [ ! -d $VR_INADYN ] && mkdir -p $VR_INADYN
 
 case "$1" in
-        start)
-                echo "Starting inadyn."
-                start-stop-daemon -S -x /usr/sbin/inadyn
-                ;;
-        stop)
-                echo  "Stopping inadyn."
-                start-stop-daemon -q -K -x /usr/sbin/inadyn
-                rm -f /var/run/inadyn/inadyn.pid
-                ;;
-        restart)
-                "$0" stop
-                "$0" start
-                ;;
-        *)
-                echo $"Usage: $0 {start|stop|restart}"
-                exit 1
+	start)
+		echo "Starting inadyn: "
+		start-stop-daemon -S -x /usr/bin/inadyn
+		[ $? == 0 ] && echo "OK" || echo "FAIL"
+		;;
+	stop)
+		echo  "Stopping inadyn: "
+		start-stop-daemon -q -K -x /usr/bin/inadyn
+		[ $? == 0 ] && echo "OK" || echo "FAIL"
+		rm -f /var/run/inadyn/inadyn.pid
+		;;
+	restart)
+		"$0" stop
+		"$0" start
+		;;
+		*)
+		echo $"Usage: $0 {start|stop|restart}"
+		exit 1
 esac
 
 exit $?
-
