netkittelnet: fix build on toolchains without C++ support
The configure script checks for C++ support as telnet (but not telnetd)
contains C++ code. This used to work by accident if the host had g++,
as we didn't pass TARGET_CONFIGURE_OPTS to configure (which sets CXX to
/bin/false).

Fix it by removing the g++ check and rewriting the configure checks to
use the C compiler instead.

Signed-off-by: Peter Korsgaard <jacmet@sunsite.dk>

diff --git a/package/netkittelnet/netkittelnet.patch b/package/netkittelnet/netkittelnet.patch
--- a/package/netkittelnet/netkittelnet.patch
+++ b/package/netkittelnet/netkittelnet.patch
@@ -24,14 +24,25 @@
         ) >/dev/null 2>&1 || continue;
         CXX=$TRY
         break;
-@@ -141,7 +138,6 @@
-     echo -n 'Checking if C++ compiler works... '
-     if (
-           $CXX __conftest.cc -o __conftest || exit 1
+@@ -138,18 +135,5 @@
+     fi
+     echo "$CXX"
+-else
+-    echo -n 'Checking if C++ compiler works... '
+-    if (
+-          $CXX __conftest.cc -o __conftest || exit 1
 -          ./__conftest || exit 1
-        ) >/dev/null 2>&1; then
-          echo 'yes'
-      else
+-       ) >/dev/null 2>&1; then
+-         echo 'yes'
+-     else
+-         echo 'no'
+-         echo 'Compiler '"$CXX"' does not exist or cannot compile C++; try another.'
+-         rm -f __conftest*
+-         exit
+-     fi
+ fi
+ 
+ echo -n "Checking if $CXX accepts gcc warnings... "
 @@ -278,13 +274,11 @@
  EOF
  if (
