package/busybox: run mdev in daemon mode
- Enable the mdev daemon mode in Busybox default config
- Update the S10mdev init script to use the daemon mode

Signed-off-by: Titouan Christophe <titouan.christophe@railnova.eu>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>

diff --git a/package/busybox/S10mdev b/package/busybox/S10mdev
--- a/package/busybox/S10mdev
+++ b/package/busybox/S10mdev
@@ -1,13 +1,17 @@
 #!/bin/sh
 #
-# Start mdev....
+# Run the mdev daemon
 #
+
+DAEMON="mdev"
+PIDFILE="/var/run/$DAEMON.pid"
 
 
 start() {
-	echo "Starting mdev..."
-	echo /sbin/mdev >/proc/sys/kernel/hotplug
-	/sbin/mdev -s
+	echo -n "Starting $DAEMON... "
+	start-stop-daemon -S -b -m -p $PIDFILE -x /sbin/mdev -- -df
+	[ $? -eq 0 ] && echo "OK" || echo "ERROR"
+
 	# coldplug modules
 	find /sys/ -name modalias -print0 | \
 		xargs -0 sort -u | \
@@ -15,12 +19,23 @@ start() {
 		xargs -0 modprobe -abq
 }
 
+stop() {
+	echo -n "Stopping $DAEMON... "
+	start-stop-daemon -K -p $PIDFILE
+	[ $? -eq 0 ] && echo "OK" || echo "ERROR"
+}
+
+restart() {
+	stop
+	start
+}
+
 case "$1" in
-  start)
+  start|stop|restart)
 	"$1"
 	;;
   *)
-	echo "Usage: $0 start"
+	echo "Usage: $0 {start|stop|restart}"
 	exit 1
 esac
 
