merged buildroot201702

diff --git a/package/nfs-utils/S60nfs b/package/nfs-utils/S60nfs
--- a/package/nfs-utils/S60nfs
+++ b/package/nfs-utils/S60nfs
@@ -17,7 +17,7 @@ CFG_FILE=/etc/default/nfsd
 
 NR_THREADS=2
 if [ -f "${CFG_FILE}" ]; then
-    . "${CFG_FILE}"
+	. "${CFG_FILE}"
 fi
 
 
@@ -25,64 +25,64 @@ start() {
 	# Start daemons.
 	printf "Starting NFS statd: "
 	rpc.statd
+	[ $? = 0 ] && echo "OK" || echo "FAIL"
 	touch /var/lock/subsys/nfslock
-	echo "done"
 
 	printf "Starting NFS services: "
 	/usr/sbin/exportfs -r
-	echo "done"
+	[ $? = 0 ] && echo "OK" || echo "FAIL"
 
 	printf "Starting NFS daemon: "
 	rpc.nfsd ${NR_THREADS}
-	echo "done"
+	[ $? = 0 ] && echo "OK" || echo "FAIL"
 
 	printf "Starting NFS mountd: "
 	rpc.mountd
-	echo "done"
+	[ $? = 0 ] && echo "OK" || echo "FAIL"
 	touch /var/lock/subsys/nfs
 }
 
 stop() {
 	# Stop daemons.
 	printf "Shutting down NFS mountd: "
-	killall -q rpc.mountd
-	echo "done"
+	killall -q rpc.mountd 2>/dev/null
+	[ $? = 0 ] && echo "OK" || echo "FAIL"
 
 	printf "Shutting down NFS daemon: "
-	kill -9 `pidof nfsd` 2>/dev/null
-	echo "done"
+	killall -q nfsd 2>/dev/null
+	[ $? = 0 ] && echo "OK" || echo "FAIL"
 
 	printf "Shutting down NFS services: "
 	/usr/sbin/exportfs -au
-	rm -f /var/lock/subsys/nfs
-	killall -q rpc.statd
-	echo "done"
+	[ $? = 0 ] && echo "OK" || echo "FAIL"
 
 	printf "Stopping NFS statd: "
-	killall -q rpc.statd
-	echo "done"
+	killall -q rpc.statd 2>/dev/null
+	[ $? = 0 ] && echo "OK" || echo "FAIL"
+	rm -f /var/lock/subsys/nfs
+	rm -f /var/run/rpc.statd.pid
 	rm -f /var/lock/subsys/nfslock
 }
 
 # See how we were called.
 case "$1" in
-  start)
-	start
-	;;
-  stop)
-	stop
-	;;
-  restart)
-	stop
-	start
-	;;
-  reload)
-	/usr/sbin/exportfs -r
-	touch /var/lock/subsys/nfs
-	;;
-  *)
-	echo "Usage: nfs {start|stop|reload}"
-	exit 1
+	start)
+		start
+		;;
+	stop)
+		stop
+		;;
+	restart)
+		stop
+		start
+		;;
+	reload)
+		/usr/sbin/exportfs -r
+		touch /var/lock/subsys/nfs
+		;;
+	*)
+		echo "Usage: $0 {start|stop|restart|reload}"
+		exit 1
 esac
 
 exit 0
