Update init scripts a bit.  Don't mess with /etc/default for now.

diff --git a/package/dhcp/init-relay b/package/dhcp/init-relay
--- a/package/dhcp/init-relay
+++ b/package/dhcp/init-relay
@@ -3,16 +3,25 @@
 # $Id: dhcp3-relay,v 1.1 2004/04/16 15:41:08 ml Exp $
 #
 
-# It is not safe to start if we don't have a default configuration...
-if [ ! -f /etc/default/dhcp-relay ]; then
-	echo "/etc/default/dhcp-relay does not exist! - Aborting..."
-	echo "create this file to fix the problem."
-	exit 1
-fi
 
-# Read init script configuration (interfaces the daemon should listen on
-# and the DHCP server we should forward requests to.)
-. /etc/default/dhcp-relay
+# What servers should the DHCP relay forward requests to?
+# e.g: SERVERS="192.168.0.1"
+SERVERS=""
+
+# On what interfaces should the DHCP relay (dhrelay) serve DHCP requests?
+INTERFACES=""
+
+# Additional options that are passed to the DHCP relay daemon?
+OPTIONS=""
+
+
+
+
+# It is not safe to start if we don't have a default configuration...
+echo "/etc/init.d/dhcp-relay not yet configured! - Aborting..."
+exit 1;
+
+
 
 # Build command line for interfaces (will be passed to dhrelay below.)
 IFCMD=""
diff --git a/package/dhcp/init-server b/package/dhcp/init-server
--- a/package/dhcp/init-server
+++ b/package/dhcp/init-server
@@ -3,17 +3,21 @@
 # $Id: dhcp3-server.init.d,v 1.4 2003/07/13 19:12:41 mdz Exp $
 #
 
-test -f /usr/sbin/dhcpd || exit 0
+
+
+# On what interfaces should the DHCP server (dhcpd) serve DHCP requests?
+#       Separate multiple interfaces with spaces, e.g. "eth0 eth1".
+INTERFACES=""
+
 
 # It is not safe to start if we don't have a default configuration...
-if [ ! -f /etc/default/dhcp-server ]; then
-	echo "/etc/default/dhcp-server does not exist! - Aborting..."
-	exit 0
-fi
+echo "/etc/init.d/dhcp-server not yet configured! - Aborting..."
+exit 1;
 
-# Read init script configuration (so far only interfaces the daemon
-# should listen on.)
-. /etc/default/dhcp-server
+
+
+test -f /usr/sbin/dhcpd || exit 0
+
 
 case "$1" in
 	start)
