Update atngw100 target skeleton

diff --git a/target/device/Atmel/atngw100/target_skeleton/etc/init.d/S01hotplug b/target/device/Atmel/atngw100/target_skeleton/etc/init.d/S01hotplug
--- a/target/device/Atmel/atngw100/target_skeleton/etc/init.d/S01hotplug
+++ b/target/device/Atmel/atngw100/target_skeleton/etc/init.d/S01hotplug
@@ -1,8 +1,8 @@
 #! /bin/sh
 
-echo -n "Setting up mdev:"
+echo -n "Setting up mdev: "
 set -e
-trap 'echo " failed"' EXIT
+trap 'echo "failed"' EXIT
 /bin/ln -s /proc/self/fd /dev/fd
 /bin/ln -s /proc/self/fd/0 /dev/stdin
 /bin/ln -s /proc/self/fd/1 /dev/stdout
@@ -11,4 +11,4 @@ trap 'echo " failed"' EXIT
 /bin/echo /sbin/mdev > /proc/sys/kernel/hotplug
 /sbin/mdev -s
 trap - EXIT
-echo " done"
+echo "done"
diff --git a/target/device/Atmel/atngw100/target_skeleton/etc/init.d/S02hostname b/target/device/Atmel/atngw100/target_skeleton/etc/init.d/S02hostname
--- a/target/device/Atmel/atngw100/target_skeleton/etc/init.d/S02hostname
+++ b/target/device/Atmel/atngw100/target_skeleton/etc/init.d/S02hostname
@@ -2,8 +2,8 @@
 
 PROGRAM=/bin/hostname
 
-echo -n "Setting hostname:"
-[ -x ${PROGRAM} ] || (echo " missing"; exit 0)
+echo -n "Setting hostname: "
+[ -x ${PROGRAM} ] || (echo "missing"; exit 0)
 
 if [ -f /etc/hostname ]; then
 	HOST="$(cat /etc/hostname)"
@@ -12,10 +12,10 @@ else
 fi
 
 start() {
-	if ${PROGRAM} "${HOST}" > /dev/null 2> /dev/null; then
-		echo " '${HOST}'"
+	if ${PROGRAM} "${HOST}"; then
+		echo "'${HOST}'"
 	else
-		echo " failed"
+		echo "failed"
 		exit 1
 	fi
 }
